ALTER TABLE message ADD COLUMN timestamp TIMESTAMP WITH TIME ZONE NOT NULL;
ALTER TABLE message DROP COLUMN time;
ALTER TABLE attachment ADD COLUMN timestamp TIMESTAMP WITH TIME ZONE NOT NULL;
ALTER TABLE icon ADD COLUMN timestamp TIMESTAMP WITH TIME ZONE NOT NULL;
ALTER TABLE react ADD COLUMN timestamp TIMESTAMP WITH TIME ZONE NOT NULL;
ALTER TABLE "user"
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ADD COLUMN last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL;