ALTER TABLE "user"
ADD COLUMN deleted_at TIMESTAMPTZ;

ALTER TABLE message
ADD COLUMN deleted_at TIMESTAMPTZ;

ALTER TABLE channel
ADD COLUMN deleted_at TIMESTAMPTZ;

ALTER TABLE category
ADD COLUMN deleted_at TIMESTAMPTZ;
